### ISSUE TITLE
Building docker images for spring boot applications without Dockerfile, directly on pom.xml

### ISSUE THREAD

**Issue by pedroluiznogueira** [fmarchioni/masterspringboot#9]
Hey, I've found your tutorials very interisting and I would like to suggest an example of creating docker images for spring boot applications directly on pom.xml.

In case you want any contributions, I could definetely implement this.

Thanks for your efforts!

**Comment by pedroluiznogueira** [comment]
Hey, yes I do. I just uploaded a repo with the sample usage. It is kind of like the same thing, but it is another alternative, sometimes it is easier and more intuitive.

Sample project:

- https://github.com/pedroluiznogueira/docker-pom-example

You just have to use put it on your build dependency:

![image](https://user-images.githubusercontent.com/81788112/156243050-c33a4c0d-4429-4fa3-b9f2-5f17a2cfa6c8.png)

- that way you just update the project version on your pom.xml, and you are good to version your image

- to build it, you run:

<b>./mvnw spring-boot:build-image</b>

- and it will run the tests aswell, so if you don't want it, you just run:

<b>./mvnw spring-boot:build-image -DskipTests</b>

I hope it helps, thanks for answering me! :)

**Comment by fmarchioni** [comment]
Thanks a lot Pedro. I've tried and it works pretty well! I'll be more than
glad to recommend this option.
As credit for your collaboration, would you like to add something about you
? (email, your current role..) I will include it at the end of the article
Thanks again

Il giorno mar 1 mar 2022 alle ore 21:28 Pedro Luiz ***@***.***>
ha scritto:

**Comment by pedroluiznogueira** [comment]
Yeah, sure, it would be great. 

<br>

Email: peluiznogueiram@hotmail.com
Current role: Java Software Engineer

<br>

If you need any kind of further contributions  I would be glad to do so. I'm always looking forward to helping on open source projects.

So, if you need it, let me know.

**Comment by fmarchioni** [comment]
Done it:
http://www.masterspringboot.com/cloud/docker/running-a-spring-boot-application-with-docker
thanks & regards
Francesco

Il giorno gio 3 mar 2022 alle ore 17:44 Pedro Luiz ***@***.***>
ha scritto:
